[project]

name = "gossip"
version = "0.1.0"
authors = [ "Daniel Fagnan <dnfagnan@gmail.com>" ]

[[lib]]

name = "gossip"
path = "src/gossip/lib.rs"

[dependencies.bencode]

git = "https://github.com/arjantop/rust-bencode.git"
